# Generated by Django 6.0 on 2026-05-01 06:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
        ('customers', '0002_alter_customer_unique_together_alter_customer_branch_and_more'),
        ('jobs', '0005_seed_dropdown_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_1_days', models.PositiveIntegerField(default=90, help_text='First reminder X days after delivery')),
                ('reminder_2_days', models.PositiveIntegerField(default=180, help_text='Second reminder X days after delivery')),
                ('reminder_3_days', models.PositiveIntegerField(default=365, help_text='Third reminder X days after delivery')),
                ('reminder_message', models.TextField(default="Hello {customer_name}, it's been {days} days since your {device_type} was serviced at {branch_name}. Book your next service now!", help_text='Reminder message template. Variables: {customer_name}, {days}, {device_type}, {branch_name}, {job_number}')),
                ('send_whatsapp', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_review_link', models.URLField(blank=True, help_text='Google Maps review link for your business')),
                ('send_after_hours', models.PositiveIntegerField(default=24, help_text='Send review request X hours after delivery')),
                ('review_message', models.TextField(default="Thank you {customer_name} for choosing {branch_name}! We'd love your feedback. Please leave us a Google review: {review_link}", help_text='Review request template. Variables: {customer_name}, {branch_name}, {review_link}')),
                ('send_whatsapp', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_config', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='customers.customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='jobs.jobcard')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit (Customer owes us)'), ('DEBIT', 'Debit (We owe customer / Payment received)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('reference_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('PAYMENT', 'Payment Received'), ('ADJUSTMENT', 'Manual Adjustment'), ('REFUND', 'Refund'), ('ADVANCE', 'Advance Payment')], default='ADJUSTMENT', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Related invoice/payment ID', max_length=100)),
                ('entry_date', models.DateField()),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance after this entry (positive = customer owes)', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer ledger entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'entry_date'], name='marketing_c_custome_3ee8e1_idx'), models.Index(fields=['branch', 'customer'], name='marketing_c_branch__352eb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('REMINDER_1', 'First Reminder'), ('REMINDER_2', 'Second Reminder'), ('REMINDER_3', 'Third Reminder')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], default='WHATSAPP', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='customers.customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='jobs.jobcard')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['branch', 'scheduled_date', 'status'], name='marketing_s_branch__77b642_idx'), models.Index(fields=['customer'], name='marketing_s_custome_4564c2_idx')],
            },
        ),
    ]
