# Generated by Django 6.0.5 on 2026-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_user_onboarding_dismissed"),
        (
            "customers",
            "0002_alter_customer_unique_together_alter_customer_branch_and_more",
        ),
        ("jobs", "0014_jobcard_delivery_otp_attempts_and_more"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="servicereminder",
            constraint=models.UniqueConstraint(
                fields=("job", "reminder_type"), name="unique_job_service_reminder"
            ),
        ),
    ]
