# Generated by Django 6.0 on 2026-01-06 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OVERDUE_JOB', 'Overdue Job'), ('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_APPROVAL', 'Pending Approval'), ('SYSTEM', 'System Alert')], max_length=30)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_alerts', to='core.branch')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('JOB_CREATED', 'Job Created'), ('JOB_DIAGNOSED', 'Job Diagnosed'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('JOB_READY', 'Job Ready for Pickup'), ('DELIVERY_OTP', 'Delivery OTP'), ('JOB_DELIVERED', 'Job Delivered'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('CUSTOM', 'Custom Message')], max_length=30)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('INTERNAL', 'Internal Alert')], max_length=20)),
                ('recipient_mobile', models.CharField(blank=True, max_length=15)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider_response', models.JSONField(blank=True, help_text='Response from SMS/WhatsApp provider', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.branch')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='billing.invoice')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='jobs.jobcard')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'notification_type'], name='notificatio_branch__65c949_idx'), models.Index(fields=['status'], name='notificatio_status_a242db_idx'), models.Index(fields=['created_at'], name='notificatio_created_01830a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('JOB_CREATED', 'Job Created'), ('JOB_DIAGNOSED', 'Job Diagnosed'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('JOB_READY', 'Job Ready for Pickup'), ('DELIVERY_OTP', 'Delivery OTP'), ('JOB_DELIVERED', 'Job Delivered'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('CUSTOM', 'Custom Message')], max_length=30)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('INTERNAL', 'Internal Alert')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject line (for email)', max_length=255)),
                ('template_text', models.TextField(help_text='Template text with placeholders. Available: {customer_name}, {job_number}, {branch_name}, {device}, {status}, {amount}, {otp}, {invoice_number}')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.branch')),
            ],
            options={
                'ordering': ['notification_type', 'channel'],
                'unique_together': {('branch', 'notification_type', 'channel')},
            },
        ),
    ]
