# Generated by Django 6.0.5 on 2026-08-12 07:54

import django.db.models.deletion
from django.db import migrations, models


def seed_credit_note_template(apps, schema_editor):
    Branch = apps.get_model("core", "Branch")
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    template_text = (
        "Credit Note {credit_note_number} for ₹{amount} has been issued against "
        "Invoice {invoice_number}. Please contact {branch_name} if you have questions."
    )
    for branch in Branch.objects.all().iterator():
        NotificationTemplate.objects.get_or_create(
            branch=branch,
            notification_type="CREDIT_NOTE_ISSUED",
            channel="SMS",
            defaults={"template_text": template_text, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_invoice_customer"),
        ("notifications", "0002_seed_default_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="credit_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="billing.creditnote",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("JOB_CREATED", "Job Created"),
                    ("JOB_DIAGNOSED", "Job Diagnosed"),
                    ("ESTIMATE_SHARED", "Estimate Shared"),
                    ("JOB_READY", "Job Ready for Pickup"),
                    ("DELIVERY_OTP", "Delivery OTP"),
                    ("JOB_DELIVERED", "Job Delivered"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PAYMENT_REMINDER", "Payment Reminder"),
                    ("CREDIT_NOTE_ISSUED", "Credit Note Issued"),
                    ("LOW_STOCK_ALERT", "Low Stock Alert"),
                    ("CUSTOM", "Custom Message"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("JOB_CREATED", "Job Created"),
                    ("JOB_DIAGNOSED", "Job Diagnosed"),
                    ("ESTIMATE_SHARED", "Estimate Shared"),
                    ("JOB_READY", "Job Ready for Pickup"),
                    ("DELIVERY_OTP", "Delivery OTP"),
                    ("JOB_DELIVERED", "Job Delivered"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PAYMENT_REMINDER", "Payment Reminder"),
                    ("CREDIT_NOTE_ISSUED", "Credit Note Issued"),
                    ("LOW_STOCK_ALERT", "Low Stock Alert"),
                    ("CUSTOM", "Custom Message"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(seed_credit_note_template, migrations.RunPython.noop),
    ]
