# render.yaml (put in project root)
services:
  - type: web
    name: servicehub-backend1
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://service-center-management.vercel.app"
      - key: CORS_ALLOW_VERCEL
        value: "True"
