# Generated by Django 6.0 on 2026-03-10 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        ('core', '0002_rolepermission_organization_authorized_signatory_and_more'),
        ('jobs', '0003_jobcard_additional_comments_alter_jobcard_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='jobs.jobcard'),
        ),
        migrations.CreateModel(
            name='InvoiceEditHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edit_type', models.CharField(choices=[('CREATED', 'Invoice Created'), ('LINE_ITEM_ADDED', 'Line Item Added'), ('LINE_ITEM_REMOVED', 'Line Item Removed'), ('LINE_ITEM_UPDATED', 'Line Item Updated'), ('AMOUNTS_UPDATED', 'Amounts Updated'), ('DETAILS_UPDATED', 'Details Updated'), ('STATUS_CHANGED', 'Status Changed'), ('DOWNLOADED', 'Invoice Downloaded'), ('CANCELLED', 'Invoice Cancelled')], max_length=30)),
                ('summary', models.CharField(help_text='Human-readable description of the change', max_length=500)),
                ('old_values', models.JSONField(blank=True, help_text='Snapshot of values before the change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Snapshot of values after the change', null=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_edits', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='billing.invoice')),
            ],
            options={
                'verbose_name_plural': 'Invoice edit histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
