# Generated by Django 6.0.5 on 2026-05-09 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_branch_alter_invoice_job_and_more'),
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
        ('jobs', '0005_seed_dropdown_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', 'invoice_date'], name='billing_inv_branch__e2e1f6_idx'),
        ),
    ]
