# Generated by Django 6.0 on 2026-05-01 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
        ('customers', '0002_alter_customer_unique_together_alter_customer_branch_and_more'),
        ('jobs', '0005_seed_dropdown_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Name of prospect', max_length=255)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('problem_description', models.TextField(help_text='What the customer described as the issue')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted to the customer', max_digits=10, null=True)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('PHONE_CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('GOOGLE', 'Google Search'), ('SOCIAL_MEDIA', 'Social Media'), ('REFERRAL', 'Referral'), ('JUSTDIAL', 'JustDial'), ('SULEKHA', 'Sulekha'), ('OTHER', 'Other')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow-up Scheduled'), ('INTERESTED', 'Interested'), ('QUOTED', 'Quote Shared'), ('CONVERTED', 'Converted to Job'), ('LOST', 'Lost / Declined'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, help_text='Next follow-up date', null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('loss_reason', models.CharField(blank=True, choices=[('PRICE_HIGH', 'Price too high'), ('WENT_ELSEWHERE', 'Went to competitor'), ('NOT_NEEDED', 'Repair not needed'), ('NOT_REACHABLE', 'Customer not reachable'), ('DELAYED', 'Too long wait time'), ('OTHER', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='core.branch')),
                ('converted_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_enquiry', to='jobs.jobcard')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_enquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to existing customer, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_notes', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_notes', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['branch', 'status'], name='enquiries_e_branch__59f22c_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['customer_mobile'], name='enquiries_e_custome_a42fba_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['follow_up_date'], name='enquiries_e_follow__1c50fa_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['source'], name='enquiries_e_source_e3f035_idx'),
        ),
    ]
