# Generated by Django 6.0 on 2026-01-06 18:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{9,14}$', message='Enter a valid mobile number')])),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{9,14}$', message='Enter a valid mobile number')])),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit pincode')])),
                ('state_code', models.CharField(blank=True, help_text='GST State Code for interstate supply determination', max_length=2)),
                ('gstin', models.CharField(blank=True, help_text="Customer's GSTIN for B2B invoices", max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sms_enabled', models.BooleanField(default=True, help_text='Send SMS notifications to this customer')),
                ('whatsapp_enabled', models.BooleanField(default=True, help_text='Send WhatsApp notifications to this customer')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about customer')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='core.branch')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('OTHER', 'Other')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='customer_documents/')),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch', 'mobile'], name='customers_c_branch__d8ece0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['mobile'], name='customers_c_mobile_e14eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch', 'first_name', 'last_name'], name='customers_c_branch__70d109_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('branch', 'mobile')},
        ),
    ]
