# Generated by Django 6.0 on 2026-05-06 09:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='HSN or SAC code (e.g. 998711 or 84733099)', max_length=10, unique=True)),
                ('code_type', models.CharField(choices=[('HSN', 'HSN — Goods'), ('SAC', 'SAC — Services')], default='SAC', max_length=3)),
                ('description', models.CharField(help_text='Description of goods/service', max_length=255)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default GST rate for this code (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HSN/SAC Code',
                'verbose_name_plural': 'HSN/SAC Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GSTPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField(help_text='Month this payment covers (use first day of month)')),
                ('cgst_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sgst_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_date', models.DateField()),
                ('challan_number', models.CharField(blank=True, help_text='Challan Reference Number (CRN)', max_length=100)),
                ('payment_method', models.CharField(choices=[('NEFT', 'NEFT/RTGS'), ('UPI', 'UPI'), ('CASH', 'Cash at Bank'), ('DEBIT_CARD', 'Debit Card'), ('OTHER', 'Other')], default='NEFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_payments', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_payments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Payment',
                'ordering': ['-period_month', '-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='GSTReturnStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField(help_text='First day of the return period month')),
                ('gstr1_filed', models.BooleanField(default=False)),
                ('gstr1_filed_at', models.DateTimeField(blank=True, null=True)),
                ('gstr3b_filed', models.BooleanField(default=False)),
                ('gstr3b_filed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_return_statuses', to='core.branch')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_returns_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Return Status',
                'ordering': ['-period_month'],
                'unique_together': {('branch', 'period_month')},
            },
        ),
    ]
