# Generated by Django 6.0 on 2026-01-06 18:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='core.branch')),
            ],
            options={
                'verbose_name_plural': 'Inventory categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price (purchase price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price to customers', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST rate percentage', max_digits=5)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN/SAC code for GST', max_length=8)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this level')),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('NOS', 'Numbers'), ('MTR', 'Meters'), ('SET', 'Set'), ('BOX', 'Box'), ('KG', 'Kilogram')], default='PCS', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Storage location in branch', max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_contact', models.CharField(blank=True, max_length=100)),
                ('warranty_period_months', models.PositiveIntegerField(default=0, help_text='Warranty period in months (0 = no warranty)')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Stock Added'), ('DEDUCT', 'Stock Deducted'), ('MANUAL', 'Manual Adjustment'), ('CORRECTION', 'Stock Correction'), ('RETURN', 'Stock Return'), ('DAMAGED', 'Damaged/Lost')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('is_manual_adjustment', models.BooleanField(default=False)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPartUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of use', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity × unit_price)', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_usage', to='inventory.inventoryadjustment')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_usages', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
