# Generated by Django 6.0 on 2026-01-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpartusage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_usages', to='jobs.jobcard'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='core.branch'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='core.branch'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='inventory_item',
            field=models.ForeignKey(help_text='Item from source branch', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch', 'name'], name='inventory_i_branch__727932_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch', 'sku'], name='inventory_i_branch__dd2d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['quantity', 'low_stock_threshold'], name='inventory_i_quantit_fb9064_idx'),
        ),
    ]
