# Generated by Django 6.0 on 2026-03-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_organization_authorized_signatory_and_more'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.branch'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_branch_category_name'),
        ),
    ]
