# Generated by Django 6.0 on 2026-05-01 06:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / Wi-Fi'), ('SALARY', 'Staff Salary'), ('TEA_SNACKS', 'Tea / Snacks / Meals'), ('TRANSPORT', 'Transport / Fuel'), ('STATIONERY', 'Stationery / Printing'), ('TOOLS', 'Tools & Equipment'), ('MAINTENANCE', 'Shop Maintenance'), ('MARKETING', 'Marketing / Advertising'), ('INSURANCE', 'Insurance'), ('TAX', 'Tax / Government Fees'), ('MISCELLANEOUS', 'Miscellaneous')], default='MISCELLANEOUS', max_length=20)),
                ('title', models.CharField(help_text='Short description of the expense', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed notes about the expense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(help_text='Date the expense was incurred')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NEFT', 'NEFT/RTGS'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt/bill photo', null=True, upload_to='expense_receipts/%Y/%m/')),
                ('is_recurring', models.BooleanField(default=False, help_text='Mark as a recurring monthly expense')),
                ('vendor_name', models.CharField(blank=True, help_text='Name of vendor/payee', max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'expense_date'], name='expenses_ex_branch__593f12_idx'), models.Index(fields=['branch', 'category'], name='expenses_ex_branch__e8e045_idx'), models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx')],
            },
        ),
    ]
