# Generated by Django 6.0 on 2026-05-06 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST paid (auto-calculated)', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST rate applied on this expense (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_itc_eligible',
            field=models.BooleanField(default=False, help_text='Claim Input Tax Credit on this expense?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST paid (auto-calculated)', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxable amount (before GST)', max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_gstin',
            field=models.CharField(blank=True, help_text='Vendor GSTIN (required to claim ITC)', max_length=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, help_text="Vendor's invoice/bill number", max_length=100),
        ),
    ]
