# Generated by Django 6.0 on 2026-01-06 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(help_text='Auto-generated branch-scoped job number', max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('MONITOR', 'Monitor'), ('PRINTER', 'Printer'), ('UPS', 'UPS'), ('OTHER', 'Other')], default='LAPTOP', max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('_device_password', models.TextField(blank=True, db_column='device_password', help_text='Encrypted device password')),
                ('_bios_password', models.TextField(blank=True, db_column='bios_password', help_text='Encrypted BIOS password')),
                ('customer_complaint', models.TextField(help_text="Customer's description of the problem")),
                ('physical_condition', models.TextField(help_text='Physical condition of device on receipt (scratches, dents, etc.)')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('DIAGNOSED', 'Diagnosed'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('READY', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20)),
                ('diagnosis_notes', models.TextField(blank=True, help_text='Internal diagnosis notes (not shared with customer)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated repair cost', max_digits=10, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('customer_approval_date', models.DateTimeField(blank=True, help_text='When customer approved the estimate', null=True)),
                ('customer_rejection_reason', models.TextField(blank=True, help_text='Reason if customer rejected repair')),
                ('completion_notes', models.TextField(blank=True, help_text='Work done notes')),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_otp', models.CharField(blank=True, help_text='OTP for device delivery', max_length=6)),
                ('delivery_signature', models.ImageField(blank=True, help_text='Customer signature at delivery', null=True, upload_to='delivery_signatures/')),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark job as urgent/priority')),
                ('is_warranty_repair', models.BooleanField(default=False, help_text='This is a warranty repair')),
                ('warranty_details', models.TextField(blank=True, help_text='Warranty claim details')),
                ('assigned_technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='customers.customer')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_jobs', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(help_text='User who received the device', on_delete=django.db.models.deletion.PROTECT, related_name='received_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAccessory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessory_type', models.CharField(choices=[('CHARGER', 'Charger/Adapter'), ('BATTERY', 'Battery'), ('BAG', 'Laptop Bag'), ('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('POWER_CABLE', 'Power Cable'), ('USB_CABLE', 'USB Cable'), ('HDMI_CABLE', 'HDMI Cable'), ('RAM', 'RAM Module'), ('HDD', 'Hard Drive'), ('SSD', 'SSD'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, help_text="Additional description for 'Other' type", max_length=255)),
                ('condition', models.CharField(blank=True, help_text='Condition of the accessory', max_length=255)),
                ('is_present', models.BooleanField(default=True, help_text='Was this accessory received with device')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='jobs.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='JobNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are not visible to customers')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.jobcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='job_photos/')),
                ('photo_type', models.CharField(choices=[('INTAKE', 'Intake Photo'), ('DAMAGE', 'Damage Photo'), ('REPAIR', 'Repair Photo'), ('COMPLETED', 'Completed Photo')], default='INTAKE', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.jobcard')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('RECEIVED', 'Received'), ('DIAGNOSED', 'Diagnosed'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('READY', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('RECEIVED', 'Received'), ('DIAGNOSED', 'Diagnosed'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('READY', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_override', models.BooleanField(default=False, help_text='True if status was changed via manual override')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Job status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(help_text='Part name (for non-inventory items)', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('USED', 'Used')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_approvals', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='jobs.jobcard')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['branch', 'status'], name='jobs_jobcar_branch__083383_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['branch', 'job_number'], name='jobs_jobcar_branch__10ad51_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['customer'], name='jobs_jobcar_custome_84f44d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['assigned_technician', 'status'], name='jobs_jobcar_assigne_e8265d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['created_at'], name='jobs_jobcar_created_e7778a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobaccessory',
            unique_together={('job', 'accessory_type')},
        ),
    ]
