# Generated by Django 6.0 on 2026-03-10 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_organization_authorized_signatory_and_more'),
        ('customers', '0002_alter_customer_unique_together_alter_customer_branch_and_more'),
        ('jobs', '0002_alter_jobcard_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Additional comments or notes'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='core.branch'),
        ),
        migrations.CreateModel(
            name='DiagnosisPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Part name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('warranty_months', models.PositiveIntegerField(default=0, help_text='Warranty in months')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_parts', to='jobs.jobcard')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_number', models.CharField(help_text='Auto-generated pickup request number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('PICKED_UP', 'Picked Up'), ('DELIVERED_TO_CENTER', 'Delivered to Center'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=25)),
                ('device_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('MONITOR', 'Monitor'), ('PRINTER', 'Printer'), ('UPS', 'UPS'), ('OTHER', 'Other')], default='LAPTOP', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('customer_complaint', models.TextField(help_text='Issue described by customer on the call')),
                ('pickup_address', models.TextField(help_text='Full address for device pickup')),
                ('pickup_date', models.DateField(help_text='Scheduled pickup date')),
                ('pickup_time_slot', models.CharField(blank=True, help_text='Preferred time slot (e.g. 10:00 AM - 12:00 PM)', max_length=50)),
                ('contact_number', models.CharField(help_text='Contact number for pickup', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from staff')),
                ('is_urgent', models.BooleanField(default=False, help_text='Priority pickup')),
                ('assigned_technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to='core.branch')),
                ('created_by', models.ForeignKey(help_text='Staff who created the pickup request', on_delete=django.db.models.deletion.PROTECT, related_name='created_pickups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to='customers.customer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='jobs.jobcard')),
            ],
            options={
                'ordering': ['-is_urgent', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='jobs_pickup_branch__1784a8_idx'), models.Index(fields=['assigned_technician', 'status'], name='jobs_pickup_assigne_307b8b_idx'), models.Index(fields=['customer'], name='jobs_pickup_custome_4ebda8_idx'), models.Index(fields=['pickup_date'], name='jobs_pickup_pickup__c54bfb_idx')],
            },
        ),
    ]
