# Generated by Django 6.0 on 2026-03-19 04:52

import uuid
from django.db import migrations, models


def convert_physical_condition_to_json(apps, schema_editor):
    """Convert existing text physical_condition values to JSON format."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Update any existing text values to JSON format
        cursor.execute("""
            UPDATE jobs_jobcard
            SET physical_condition = '{}'
            WHERE physical_condition IS NULL
               OR physical_condition = ''
               OR physical_condition::text = 'null'
        """)
        # For rows with actual text values, wrap them in a JSON object
        cursor.execute("""
            UPDATE jobs_jobcard
            SET physical_condition = jsonb_build_object('legacy_text', physical_condition::text)
            WHERE physical_condition IS NOT NULL
              AND physical_condition != ''
              AND physical_condition::text != '{}'
              AND physical_condition::text != 'null'
              AND NOT (physical_condition::text LIKE '{%')
        """)


def reverse_convert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcard_additional_comments_alter_jobcard_branch_and_more'),
    ]

    operations = [
        # Step 1: Create the DropdownOption model first
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PHYSICAL_CONDITION', 'Physical Condition'), ('ENGINEER_DIAGNOSIS', 'Engineer Diagnosis')], db_index=True, help_text='Which dropdown this option belongs to', max_length=30)),
                ('device_type', models.CharField(blank=True, choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('MONITOR', 'Monitor'), ('PRINTER', 'Printer'), ('UPS', 'UPS'), ('OTHER', 'Other')], help_text='If set, option only shows for this device type. NULL = show for all.', max_length=20, null=True)),
                ('label', models.CharField(help_text='Display label for this option', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options are hidden from dropdowns')),
                ('has_text_input', models.BooleanField(default=False, help_text="If True, shows a text input when this option is selected (e.g. 'Others')")),
            ],
            options={
                'ordering': ['category', 'device_type', 'display_order', 'label'],
                'indexes': [models.Index(fields=['category', 'device_type', 'is_active'], name='jobs_dropdo_categor_1ed501_idx')],
            },
        ),
        # Step 2: Add engineer_diagnosis field
        migrations.AddField(
            model_name='jobcard',
            name='engineer_diagnosis',
            field=models.JSONField(blank=True, default=dict, help_text='Engineer diagnosis selections and optional text'),
        ),
        # Step 3: Convert existing text data to JSON before altering the column
        migrations.RunPython(convert_physical_condition_to_json, reverse_convert),
        # Step 4: Now safely alter physical_condition to JSONField
        migrations.AlterField(
            model_name='jobcard',
            name='physical_condition',
            field=models.JSONField(blank=True, default=dict, help_text='Physical condition selections and optional text'),
        ),
    ]
