# Generated by Django 6.0.5 on 2026-05-09 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
        ('customers', '0002_alter_customer_unique_together_alter_customer_branch_and_more'),
        ('jobs', '0005_seed_dropdown_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['branch', 'status', 'created_at'], name='jobs_jobcar_branch__6805a7_idx'),
        ),
    ]
