# Generated by Django 6.0.5 on 2026-05-10 09:06

import random
from django.db import migrations, models


def backfill_tracking_pins(apps, schema_editor):
    JobCard = apps.get_model('jobs', 'JobCard')
    for job in JobCard.objects.filter(tracking_pin=''):
        job.tracking_pin = str(random.randint(1000, 9999))
        job.save(update_fields=['tracking_pin'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_install_transition_stored_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='tracking_pin',
            field=models.CharField(blank=True, default='', help_text='Customer-facing PIN for public job tracking (digits only)', max_length=4),
        ),
        migrations.RunPython(backfill_tracking_pins, migrations.RunPython.noop),
    ]
