# Generated by Django 6.0.5 on 2026-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_tracking_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Inward Received'), ('DIAGNOSIS', 'Under Diagnosis'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Customer Approved'), ('REJECTED', 'Customer Rejected'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('REPAIR_IN_PROGRESS', 'Repair in Progress'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobstatushistory',
            name='from_status',
            field=models.CharField(choices=[('RECEIVED', 'Inward Received'), ('DIAGNOSIS', 'Under Diagnosis'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Customer Approved'), ('REJECTED', 'Customer Rejected'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('REPAIR_IN_PROGRESS', 'Repair in Progress'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobstatushistory',
            name='to_status',
            field=models.CharField(choices=[('RECEIVED', 'Inward Received'), ('DIAGNOSIS', 'Under Diagnosis'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Customer Approved'), ('REJECTED', 'Customer Rejected'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('REPAIR_IN_PROGRESS', 'Repair in Progress'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
