# Generated by Django 6.0.5 on 2026-07-14 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobcard_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the device was actually received from the customer'),
        ),
    ]
