# Generated by Django 6.0.5 on 2026-07-14 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_authorized_signatory_and_more'),
        ('jobs', '0010_jobcard_received_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Inward Received'), ('DIAGNOSIS', 'Under Diagnosis'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Customer Approved'), ('REJECTED', 'Customer Rejected'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('REPAIR_IN_PROGRESS', 'Repair in Progress'), ('OUTSOURCED', 'Outsourced for Repair'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobstatushistory',
            name='from_status',
            field=models.CharField(choices=[('RECEIVED', 'Inward Received'), ('DIAGNOSIS', 'Under Diagnosis'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Customer Approved'), ('REJECTED', 'Customer Rejected'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('REPAIR_IN_PROGRESS', 'Repair in Progress'), ('OUTSOURCED', 'Outsourced for Repair'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobstatushistory',
            name='to_status',
            field=models.CharField(choices=[('RECEIVED', 'Inward Received'), ('DIAGNOSIS', 'Under Diagnosis'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('APPROVED', 'Customer Approved'), ('REJECTED', 'Customer Rejected'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('REPAIR_IN_PROGRESS', 'Repair in Progress'), ('OUTSOURCED', 'Outsourced for Repair'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='OutsourceVendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Vendor / shop name', max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(help_text='Primary contact number', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='What they specialize in (e.g., BGA rework, motherboard repair)', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this vendor')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch that created this vendor. NULL = shared across branches.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_vendors', to='core.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutsourcedRepair',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why the device is being outsourced')),
                ('sent_date', models.DateField(help_text='Date device was sent to vendor')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text="Vendor's estimated/quoted repair cost", max_digits=10, null=True)),
                ('expected_return_date', models.DateField(blank=True, help_text='Expected date of return from vendor', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('status', models.CharField(choices=[('SENT', 'Sent to Vendor'), ('RETURNED', 'Returned from Vendor'), ('CANCELLED', 'Cancelled')], db_index=True, default='SENT', max_length=20)),
                ('return_date', models.DateField(blank=True, help_text='Date device was received back from vendor', null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount charged by vendor', max_digits=10, null=True)),
                ('repair_outcome', models.CharField(blank=True, choices=[('REPAIRED', 'Repaired Successfully'), ('PARTIALLY_REPAIRED', 'Partially Repaired'), ('NOT_REPAIRED', 'Could Not Repair')], help_text='Result of the outsourced repair', max_length=25)),
                ('vendor_notes', models.TextField(blank=True, help_text='What the vendor reported (work done, issues found)')),
                ('vendor_invoice_number', models.CharField(blank=True, help_text="Vendor's bill/receipt reference number", max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsourced_repairs', to='core.branch')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsourced_repairs', to='jobs.jobcard')),
                ('received_by', models.ForeignKey(blank=True, help_text='Staff member who received the device back', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourced_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(help_text='Staff member who sent the device', on_delete=django.db.models.deletion.PROTECT, related_name='outsourced_sent', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='The external vendor handling this repair', on_delete=django.db.models.deletion.PROTECT, related_name='repair_jobs', to='jobs.outsourcevendor')),
            ],
            options={
                'ordering': ['-sent_date', '-created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='jobs_outsou_job_id_ce1daf_idx'), models.Index(fields=['vendor'], name='jobs_outsou_vendor__f4d534_idx')],
            },
        ),
    ]
