# Generated by Django 6.0.5 on 2026-07-31 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchase_paid_amount_purchase_status_purchasepayment'),
        ('jobs', '0011_alter_jobcard_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourcedrepair',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for warranty claim', max_length=255),
        ),
        migrations.AddField(
            model_name='outsourcedrepair',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='outsourcedrepair',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourced_repairs', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='outsourcedrepair',
            name='is_warranty_repair',
            field=models.BooleanField(default=True, help_text='Flag indicating if this is a warranty repair claim'),
        ),
        migrations.AddField(
            model_name='outsourcedrepair',
            name='item_name',
            field=models.CharField(blank=True, help_text='Name/description of item sent for warranty repair', max_length=255),
        ),
        migrations.AddField(
            model_name='outsourcedrepair',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number or invoice reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='outsourcedrepair',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outsourced_repairs', to='jobs.jobcard'),
        ),
    ]
