# Generated by Django 6.0.5 on 2026-08-02 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_outsourcedrepair_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="received_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="The date the device was actually received from the customer",
            ),
        ),
    ]
