# Generated by Django 6.0.5 on 2026-08-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_jobcard_received_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="delivery_otp_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobcard",
            name="delivery_otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobcard",
            name="delivery_otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="delivery_otp",
            field=models.CharField(
                blank=True, help_text="Hashed OTP for device delivery", max_length=128
            ),
        ),
    ]
