# Generated by Django 6.0 on 2026-01-06 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='Action type (e.g., CREATE, UPDATE, DELETE, STATUS_CHANGE)', max_length=50)),
                ('model_name', models.CharField(db_index=True, help_text='Name of the model/table affected', max_length=100)),
                ('object_id', models.CharField(db_index=True, help_text='ID of the affected object', max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values (for updates)')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values (for updates)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('REPORT', 'Report'), ('INVOICE_PDF', 'Invoice PDF'), ('EXCEL', 'Excel Export'), ('CSV', 'CSV Export')], max_length=50)),
                ('report_name', models.CharField(max_length=255)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used for the export')),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Number of records exported')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePasswordAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for accessing the password')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Device password access logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email attempted', max_length=254)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure if unsuccessful', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
