# Generated by Django 6.0 on 2026-01-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexportlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicepasswordaccesslog',
            name='accessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_password_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
