# Generated by Django 6.0 on 2026-01-06 18:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(help_text='Legal entity name for invoices', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{1,14}$', message='Enter a valid phone number')])),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit pincode')])),
                ('country', models.CharField(default='India', max_length=100)),
                ('pan_number', models.CharField(help_text='PAN Number (e.g., ABCDE1234F)', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}\\d{4}[A-Z]$', message='Enter a valid PAN')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_organi_name_d0cc3b_idx'), models.Index(fields=['is_active'], name='core_organi_is_acti_9518a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short code for branch (used in job/invoice numbers)', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{1,14}$', message='Enter a valid phone number')])),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit pincode')])),
                ('gstin', models.CharField(help_text='GST Identification Number (e.g., 27ABCDE1234F1Z5)', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', message='Enter a valid GSTIN')])),
                ('state_code', models.CharField(help_text='GST State Code (first 2 digits of GSTIN)', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', message='Enter a valid 2-digit state code')])),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=10)),
                ('invoice_current_number', models.PositiveIntegerField(default=0, help_text='Current invoice number counter')),
                ('jobcard_prefix', models.CharField(default='JC', help_text='Prefix for job card numbers', max_length=10)),
                ('jobcard_current_number', models.PositiveIntegerField(default=0, help_text='Current job card number counter')),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Default GST rate percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{1,14}$', message='Enter a valid phone number')])),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('TECHNICIAN', 'Technician'), ('ACCOUNTANT', 'Accountant')], default='TECHNICIAN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches this user has access to (Owners have access to all)', related_name='users', to='core.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_branch', models.ForeignKey(help_text='Currently selected branch context', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'is_active'], name='core_branch_organiz_c058ee_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='core_branch_code_b50af7_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['gstin'], name='core_branch_gstin_bc3681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='core_user_organiz_72d006_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='core_user_is_acti_8c954f_idx'),
        ),
    ]
