# Generated by Django 6.0 on 2026-03-10 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('TECHNICIAN', 'Technician'), ('ACCOUNTANT', 'Accountant')], help_text='The role this permission set applies to', max_length=20, unique=True)),
                ('can_view_dashboard', models.BooleanField(default=True, help_text='Can access the dashboard')),
                ('can_view_job_cards', models.BooleanField(default=False, help_text='Can view job cards')),
                ('can_create_job_cards', models.BooleanField(default=False, help_text='Can create new job cards')),
                ('can_edit_job_cards', models.BooleanField(default=False, help_text='Can edit/update job cards')),
                ('can_view_inventory', models.BooleanField(default=False, help_text='Can view inventory items')),
                ('can_manage_inventory', models.BooleanField(default=False, help_text='Can add/edit/delete inventory')),
                ('can_view_billing', models.BooleanField(default=False, help_text='Can view invoices and payments')),
                ('can_create_invoices', models.BooleanField(default=False, help_text='Can create invoices')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Can view financial reports')),
                ('can_manage_branches', models.BooleanField(default=False, help_text='Can create/edit branches')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can create/edit/deactivate users')),
                ('can_view_pickups', models.BooleanField(default=False, help_text='Can view pickup requests')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='authorized_signatory',
            field=models.CharField(blank=True, default='', help_text='Name shown as authorized signatory on invoices', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='organization_favicons/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='invoice_notes',
            field=models.TextField(blank=True, default='', help_text='Default footer notes for invoices'),
        ),
        migrations.AddField(
            model_name='organization',
            name='invoice_terms',
            field=models.TextField(blank=True, default='', help_text='Default terms & conditions for invoices'),
        ),
        migrations.AddField(
            model_name='organization',
            name='jobcard_terms',
            field=models.TextField(blank=True, default='', help_text='Default terms for job card printouts'),
        ),
        migrations.AddField(
            model_name='organization',
            name='jobcard_warranty_text',
            field=models.TextField(blank=True, default='', help_text='Default warranty text for job cards'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#6366f1', help_text='Hex color for UI branding (e.g., #6366f1)', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, default='Management System', help_text='Shown below org name in sidebar', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text='UPI ID for payment QR code on invoices', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number (e.g., 27ABCDE1234F1Z5)', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', message='Enter a valid GSTIN')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', help_text='Prefix for invoice numbers', max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='jobcard_prefix',
            field=models.CharField(blank=True, default='JC', help_text='Prefix for job card numbers', max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state_code',
            field=models.CharField(blank=True, help_text='GST State Code (first 2 digits of GSTIN)', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', message='Enter a valid 2-digit state code')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to (null for Super Admins)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('TECHNICIAN', 'Technician'), ('ACCOUNTANT', 'Accountant')], default='TECHNICIAN', max_length=20),
        ),
    ]
