# Generated by Django 6.0.5 on 2026-05-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_last_latitude_user_last_location_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('jobcard', 'Job Card')], max_length=10)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='core.branch')),
            ],
            options={
                'unique_together': {('branch', 'kind')},
            },
        ),
    ]
