# Generated by Django 6.0.5 on 2026-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='authorized_signatory',
            field=models.CharField(blank=True, default='', help_text='Branch-specific authorized signatory name (falls back to organization defaults if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', help_text='Branch-specific bank account number (falls back to organization defaults if blank)', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_branch',
            field=models.CharField(blank=True, default='', help_text='Branch-specific bank branch name (falls back to organization defaults if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', help_text='Branch-specific bank IFSC (falls back to organization defaults if blank)', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Branch-specific bank name (falls back to organization defaults if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text='Branch-specific UPI ID for payment QR codes (falls back to organization defaults if blank)', max_length=100),
        ),
    ]
