# Generated by Django 6.0.5 on 2026-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_authorized_signatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gst_enabled',
            field=models.BooleanField(default=True, help_text='If False, GST fields will be hidden in the UI and GST will not be applied on invoices for this branch.'),
        ),
    ]
