# Generated by Django 6.0.5 on 2026-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_branchsequence_period_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchsequence",
            name="kind",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("jobcard", "Job Card"),
                    ("pickup", "Pickup"),
                    ("purchase_order", "Purchase Order"),
                    ("credit_note", "Credit Note"),
                ],
                max_length=20,
            ),
        ),
    ]
