# Generated by Django 6.0.5 on 2026-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_branchsequence_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_dismissed",
            field=models.BooleanField(default=False),
        ),
    ]
